### ISSUE TITLE
Problems launching the application

### ISSUE THREAD

**Issue by kadarsys** [open-rpc/mock-server#353]
```
 internal/modules/cjs/loader.js:883
   throw err;
  ^

 Error: Cannot find module 'commander'
 Require stack:
 - /usr/local/lib/node_modules/@open-rpc/mock-server/build/cli.js
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
     at Module.require (internal/modules/cjs/loader.js:952:19)
     at require (internal/modules/cjs/helpers.js:88:18)
     at Object.<anonymous> (/usr/local/lib/node_modules/@open-rpc/mock-server/build/cli.js:59:15)
     at Module._compile (internal/modules/cjs/loader.js:1063:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
     at Module.load (internal/modules/cjs/loader.js:928:32)
     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [ '/usr/local/lib/node_modules/@open-rpc/mock-server/build/cli.js' ]
| }
```

Hi! 
After `npm install -g @ open-rpc / mock-server` when I try to run `npm run mock-server` I get this error. Tried different installation options - nothing helped.

`npm install -g commander` solves the problem partially. But the same shouldn't be?

Check, please.

(OS Windows 10 PRO build 19041, node v11.14.0, npm 6.7.0)

**Comment by shanejonas** [comment]
hi @kadarsys 

sounds like you are trying to use it 2 different ways

to use globally:

```
npm install -g @open-rpc/mock-server
open-rpc-mock-server --help
```

to use in your project:

```
npm install @open-rpc/mock-server --save
node_modules/.bin/open-rpc-mock-server --help
```

OR for locally: put it in your package.json
```
npm install @open-rpc/mock-server --save

//...snip
"scripts": {
  "mock-server": "open-rpc-mock-server"
}
```

**Comment by BelfordZ** [comment]
thanks @kadarsys for the issue.

Ive make a new release, please give it a try. `npm install -g @open-rpc/mock-server@1.7.1`
