### ISSUE TITLE
MockServer crashes on failed parse of payload

### ISSUE THREAD

**Issue by hholst80** [open-rpc/mock-server#379]
1. Deploy a MockServer with PetShop example.

2. Post an invalid json-rpc command (typo params should be a list not an object).

```
{
	"jsonrpc": "2.0",
	"method": "rpc.discover",
	"params": {},
	"id": 0
}
```

```
(node:542) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'params' of undefined
    at sortParamKeys (/root/open-rpc/node_modules/@open-rpc/server-js/build/router.js:8:30)
    at Router.call (/root/open-rpc/node_modules/@open-rpc/server-js/build/router.js:44:66)
    at HTTPServerTransport.routerHandler (/root/open-rpc/node_modules/@open-rpc/server-js/build/transports/server-transport.js:34:42)
    at HTTPServerTransport.httpRouterHandler (/root/open-rpc/node_modules/@open-rpc/server-js/build/transports/http.js:42:34)
    at call (/root/open-rpc/node_modules/connect/index.js:239:7)
    at next (/root/open-rpc/node_modules/connect/index.js:183:5)
    at /root/open-rpc/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/root/open-rpc/node_modules/raw-body/index.js:224:16)
    at done (/root/open-rpc/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/root/open-rpc/node_modules/raw-body/index.js:273:7)
(node:542) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:542) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hholst80** [comment]
Looking here https://github.com/open-rpc/mock-server/issues/277
it looks like params should be allowed to be an object as well.
